/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views_pkg;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.time.Clock.system;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model_pkg.Conexion;

/**
 *
 * @author athen
 */
public class Menu_Inicio extends javax.swing.JFrame {
    Conexion con;
    Connection cn;
    Statement st;
    ResultSet rs;
    int id_usuario;
    DefaultTableModel model;
    /**
     * Creates new form Menu_Inicio
     */
    public Menu_Inicio(Conexion con,Connection cn,Statement st,ResultSet rs,int id_usuario,String nombre) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.con=con;
        this.cn=cn;
        this.st=st;
        this.rs=rs;
        this.id_usuario = id_usuario;
        this.mostrar_rutas();
        this.label_nombre.setText("Rutas de: "+nombre);
        System.out.println(this.id_usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_rutas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_inicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_final = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_kilometros = new javax.swing.JTextField();
        btn_empezar = new javax.swing.JButton();
        btn_terminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_finRuta = new javax.swing.JTextField();
        lista_casualidades = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_nombre.setText("Inicio");

        tb_rutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ruta", "Fecha Inicio", "Fecha FInal", "Kilometros", "Punto Inicio", "Punto Final", "Casualidad", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tb_rutas);

        jLabel2.setText("Lugar de Inicio: ");

        jLabel3.setText("Lugar de Llegada: ");

        jLabel4.setText("Kilometros: ");

        btn_empezar.setText("Empezar Ruta");
        btn_empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empezarActionPerformed(evt);
            }
        });

        btn_terminar.setText("Terminar Ruta");
        btn_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarActionPerformed(evt);
            }
        });

        jLabel5.setText("id ruta: ");

        lista_casualidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accidente", "Cierre de via", "Fallas mecanicas", "otro" }));

        jLabel6.setText("Casualidad:");

        jLabel7.setText("Descripcion:");

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane2.setViewportView(descripcion);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setText("jLabel8");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_final, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btn_empezar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lista_casualidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_finRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(label_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nombre)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btn_empezar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(16, 16, 16))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_finRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lista_casualidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_terminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empezarActionPerformed
        // TODO add your handling code here:
        this.anadir_ruta();
    }//GEN-LAST:event_btn_empezarActionPerformed

    private void btn_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarActionPerformed
        // TODO add your handling code here:
        int id_ruta = Integer.parseInt(txt_finRuta.getText());
        this.terminar_ruta();
    }//GEN-LAST:event_btn_terminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

     void clear_rows_table(){
        for(int i=0;i<tb_rutas.getRowCount();i++){
            model.removeRow(i);
            i-=1;
        }
        txt_inicio.setText("");
        txt_final.setText("");
        txt_kilometros.setText("");
    }
    
    public void mostrar_rutas(){
        
        String sql="SELECT `id`, `fecha_inicio`, `fecha_fin`, `inicio`, `fin`, `kilometros`, `casualidad`, `descripcion` FROM tb_ruta WHERE `id_usuario`='"+id_usuario+"';";
        try{
            cn=con.getConection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]hospital=new Object[8];
            model=(DefaultTableModel)tb_rutas.getModel();
            while(rs.next()){
                hospital[0]= rs.getInt("id");
                hospital[1]= rs.getDate("fecha_inicio");
                hospital[2]= rs.getDate("fecha_fin");
                hospital[3]= rs.getFloat("kilometros");
                hospital[4]= rs.getString("inicio");
                hospital[5]= rs.getString("fin");
                hospital[6]= rs.getString("casualidad");
                hospital[7]= rs.getString("descripcion");
                model.addRow(hospital);
            }
            tb_rutas.setModel(model);
            
        }catch(SQLException e){
            System.out.println(e);
        }
    
    }
    
     void anadir_ruta(){
    
        String lugar_inicial=txt_inicio.getText();
        String lugar_final=txt_final.getText();
        float kilometros=Float.parseFloat(txt_kilometros.getText());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String fecha_inicio = dtf.format(LocalDateTime.now());
        String fecha_fin = dtf.format(LocalDateTime.now());
        
        if(lugar_inicial.equals("") || lugar_final.equals("") || (kilometros == 0)){
            JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
        }else{
            String sql = "INSERT INTO `tb_ruta`(`id_usuario`, `fecha_inicio`, `fecha_fin`, `inicio`, `fin`, `kilometros`, `casualidad`, `descripcion`) VALUES ('"+id_usuario+"','"+fecha_inicio+"','"+fecha_fin+"','"+lugar_inicial+"','"+lugar_final+"','"+kilometros+"','sin terminar','NA')";
            try{
                cn=con.getConection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                this.clear_rows_table();
                JOptionPane.showMessageDialog(this, "Se ha creado el registro");
                this.mostrar_rutas();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            
            }
        }
    }
     
     void terminar_ruta(){
        int id=Integer.parseInt(txt_finRuta.getText());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String fecha_fin = dtf.format(LocalDateTime.now());
        String fecha_limite = "2021-09-05 11:59:59";
        String casualidad = (String)lista_casualidades.getSelectedItem();
        String descripcion = this.descripcion.getText();
        
        if(id == 0){
             JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
        }else if(fecha_fin.compareTo(fecha_limite) > 0){
            JOptionPane.showMessageDialog(this,"Fecha limite, no puede montar bicicleta");
        }else{
            String sql="UPDATE `tb_ruta` SET `fecha_fin`='"+fecha_fin+"',`casualidad`='"+casualidad+"',`descripcion`='"+descripcion+"' WHERE id="+id+";";
            try{
                cn = con.getConection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                clear_rows_table();
                JOptionPane.showMessageDialog(this,"Ruta terminada");
                this.mostrar_rutas();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }
     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_empezar;
    private javax.swing.JButton btn_terminar;
    private javax.swing.JTextArea descripcion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JComboBox<String> lista_casualidades;
    private javax.swing.JTable tb_rutas;
    private javax.swing.JTextField txt_finRuta;
    private javax.swing.JTextField txt_final;
    private javax.swing.JTextField txt_inicio;
    private javax.swing.JTextField txt_kilometros;
    // End of variables declaration//GEN-END:variables
}
